
package com.dao.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.0
 * Tue Apr 09 09:57:41 CEST 2019
 * Generated source version: 3.3.0
 */

@XmlRootElement(name = "creationVilleResponse", namespace = "http://dao.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creationVilleResponse", namespace = "http://dao.com/")

public class CreationVilleResponse {

    @XmlElement(name = "return")
    private boolean _return;

    public boolean getReturn() {
        return this._return;
    }

    public void setReturn(boolean new_return)  {
        this._return = new_return;
    }

}

