
package com.dao.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.0
 * Tue Apr 09 09:57:41 CEST 2019
 * Generated source version: 3.3.0
 */

@XmlRootElement(name = "listeVilles", namespace = "http://dao.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listeVilles", namespace = "http://dao.com/")

public class ListeVilles {


}

