
package com.dao.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.0
 * Tue Apr 09 09:57:41 CEST 2019
 * Generated source version: 3.3.0
 */

@XmlRootElement(name = "supprimerVille", namespace = "http://dao.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "supprimerVille", namespace = "http://dao.com/")

public class SupprimerVille {

    @XmlElement(name = "arg0")
    private com.dto.Ville arg0;

    public com.dto.Ville getArg0() {
        return this.arg0;
    }

    public void setArg0(com.dto.Ville newArg0)  {
        this.arg0 = newArg0;
    }

}

